import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from 'typescript';
import * as THREE from 'three';

const out = resolve('work/popup-test');
mkdirSync(out, { recursive: true });
for (const name of ['booth-content', 'immersive-popup', 'startups', 'profile-reader', 'profile-fields', 'booth-panels', 'exhibit-concepts', 'interest-client', 'follow-up', 'interaction-cues']) {
  const source = readFileSync(`lib/${name}.ts`, 'utf8');
  const result = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } });
  writeFileSync(`${out}/${name}.mjs`, result.outputText.replace(/(['\"])(\.\/[^'\"]+)\1/g, "$1$2.mjs$1"));
}
const { createImmersivePopup } = await import(pathToFileURL(`${out}/immersive-popup.mjs`));
const { boothJobs, investmentPreview, validInterestAmount } = await import(pathToFileURL(`${out}/booth-content.mjs`));
const { createInteractionCues } = await import(pathToFileURL(`${out}/interaction-cues.mjs`));
const { startups } = await import(pathToFileURL(`${out}/startups.mjs`));
let drawn = [];
const ctx = {
  fillRect() { drawn = []; }, beginPath() {}, roundRect() {}, fill() {}, stroke() {},
  fillText(value) { drawn.push(value); },
  measureText(value) { return { width: value.length * 17 }; },
};
globalThis.document = { createElement: () => ({ getContext: () => ctx }) };
const scene = new THREE.Scene(), camera = new THREE.PerspectiveCamera();
camera.position.set(2, 1.7, 3);
scene.add(camera);
const saved=[], followSaved=[]; let failSave=false, failFollow=false;
const popup = createImmersivePopup(scene, () => camera, async input => {if(failSave)throw Error('offline');saved.push(input);return {id:input.submissionId};}, async input => {if(failFollow)throw Error('offline');followSaved.push(input);return {id:input.submissionId};});
const card = popup.targets[0];
const click = (x, y) => card.userData.activate({ uv: new THREE.Vector2(x / 1200, 1 - y / 900) });
const has = value => drawn.some(line => line.includes(value));
popup.open(startups[0], 'meeting');
assert.equal(popup.active, true);
assert.ok(Math.abs(card.position.distanceTo(camera.position) - 1.55) < 1e-9);
popup.update(0.6,true);
const border=card.children.find(o=>o instanceof THREE.LineLoop);
assert.ok(border.visible,'Active popup offers a subtle cue');
const intersections=[];border.raycast(new THREE.Raycaster(),intersections);assert.equal(intersections.length,0,'Feedback must never intercept a controller ray');
popup.update(0.6,false);assert.equal(border.visible,false,'Reduced motion hides animated feedback');
const testScene=new THREE.Scene(), testTarget=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshBasicMaterial());
testTarget.userData.activate=()=>{};testScene.add(testTarget);
const testCamera=new THREE.PerspectiveCamera();testCamera.position.z=3;
const cues=createInteractionCues(testScene,()=>[testTarget]);const originalScale=testTarget.scale.clone(),originalPosition=testTarget.position.clone();
cues.update(1,testCamera,true,true);cues.update(1.7,testCamera,true,true);cues.click(testTarget);cues.update(performance.now()/1000,testCamera,true,true);
assert.deepEqual(testTarget.position,originalPosition);assert.deepEqual(testTarget.scale,originalScale,'Hints leave hit targets and readable content stationary');
cues.update(3,testCamera,false,true);assert.ok(testScene.children.filter(o=>o!==testTarget).every(o=>!o.visible));
cues.dispose();assert.equal(testScene.children.length,1);testTarget.geometry.dispose();testTarget.material.dispose();
const anchored = card.position.clone();
camera.rotation.y = 0.5;
assert.deepEqual(card.position, anchored, 'The panel must stay world anchored');
assert.ok(has('Request follow up'));
assert.equal(has('Event day 1'),false);assert.equal(has('10:00'),false);
click(200,350);assert.ok(has('Name (optional)'));
const keyboardRows=['1234567890','qwertzuiop','asdfghjkl@','yxcvbnm.-_',"äöüß+!'%=&"];
const key = char => {const row=keyboardRows.findIndex(r=>r.includes(char));assert.ok(row>=0);click(75+keyboardRows[row].indexOf(char)*110,340+row*80);};
click(100,760);key('j');click(100,760);key('ö');key('r');key('g');
click(350,760);key('t');key('x');click(650,760); // backspace removes x
click(950,760);assert.ok(has('Jörg t'));
click(200,505);key('t');click(950,760);click(200,760);
assert.ok(has('gültige E-Mail'));assert.equal(followSaved.length,0);
click(200,505);key('@');key('t');key('.');key('d');key('e');click(950,760);
failFollow=true;click(120,760);await new Promise(resolve=>setImmediate(resolve));
assert.ok(has('Nicht gespeichert.'));assert.equal(has('Your request has been saved'),false);
failFollow=false;click(120,760);await new Promise(resolve=>setImmediate(resolve));
assert.ok(has('Your request has been saved'));assert.equal(followSaved.length,1);
assert.equal(followSaved[0].source,'vr');assert.equal(followSaved[0].name,'Jörg t');assert.equal(followSaved[0].email,'t@t.de');
assert.equal(followSaved[0].day,undefined);assert.equal(followSaved[0].slot,undefined);
click(1040,65);assert.equal(popup.active,false);
popup.open(startups[1],'meeting');assert.ok(has('Name eingeben'));assert.ok(has('E-Mail eingeben'));
click(120,760);await new Promise(resolve=>setImmediate(resolve));assert.ok(has('Your request has been saved'));
assert.equal(followSaved[1].name,'');assert.equal(followSaved[1].email,'');
popup.open(startups[2], 'jobs');
assert.ok(has('SAMPLE ROLE'));
assert.equal(boothJobs(startups[2])[0].preview, true);
assert.equal(boothJobs(startups[0])[0].preview, false);
click(980, 790);
assert.ok(has('FOLLOW-UP REQUEST'));
assert.ok(has('Name eingeben'), 'New openings reset contact details');
const many = { ...startups[0], jobs: [
  { title: 'Long listing', location: 'Karlsruhe', url: '', description: 'Technology research and development. '.repeat(80) },
  { title: 'Second listing', location: 'Karlsruhe', url: '' },
] };
popup.open(many, 'jobs');
assert.ok(has('PAGE 1 /'));
click(350, 790);
assert.ok(has('PAGE 2 /'));
click(630, 790);
assert.ok(has('Second listing'));
assert.ok(has('ROLE 2 / 2 · PAGE 1 / 1'));
popup.open(many, 'jobs', 1);
assert.ok(has('Second listing'), 'Shelf selection opens the exact selected role');
for (const startup of startups) assert.match(investmentPreview(startup.id), /^€[\d.]+[MK]$/);
popup.open(startups[0], 'investment');
assert.ok(has('Unverbindliche Interessenbekundung'));
click(800, 790);
await new Promise(resolve=>setImmediate(resolve));
assert.equal(has('Ihre Angabe wurde gespeichert.'), false, 'Requires explicit interest selection');
click(250, 420);
assert.ok(has('25.000 €'));
assert.ok(has('Schrittweite wählen'));
click(680,550); assert.ok(has('25.100 €'), 'Default increment is 100');
click(130,665); click(680,550); assert.ok(has('25.110 €'), '10-euro increment');
click(430,550); assert.ok(has('25.100 €'), 'Minus uses selected step');
click(550,665); click(680,550); assert.ok(has('25.600 €'), '500-euro increment');
click(780,665); click(680,550); assert.ok(has('26.600 €'), '1000-euro increment');
click(1000,665); click(680,550); assert.ok(has('36.600 €'), '10000-euro increment');
for(let i=0;i<20;i++)click(680,550);
assert.ok(has('111.111 €'), 'Upper limit is clamped');
for(let i=0;i<20;i++)click(430,550);
assert.ok(has('111 €'), 'Lower limit is clamped');
click(130,665); click(680,550); assert.ok(has('121 €'), 'Fine increment from minimum');
click(800, 790);
await new Promise(resolve=>setImmediate(resolve));
assert.ok(has('Ihre Angabe wurde gespeichert.'));
assert.ok(has('121 € · unverbindlich'));
assert.ok(has('In der geschützten Tabelle'));
click(250, 790);
click(950, 550);
assert.ok(has('Ohne Betrag'));
click(800, 790);
await new Promise(resolve=>setImmediate(resolve));
assert.ok(has('Ihre Angabe wurde gespeichert.'));
assert.equal(has('121 €'), false, 'Optional amount omitted from confirmation');
popup.open(startups[1], 'investment');
click(850, 420);
click(800, 790);
await new Promise(resolve=>setImmediate(resolve));
assert.ok(has('Nein, nicht interessiert'));
assert.equal(has('25.000 €'), false, 'No-interest confirmation excludes amount');
for (const valid of ['', '111', '111.01', '25000', '111111.00']) assert.equal(validInterestAmount(valid), true);
for (const invalid of ['110', '111111.01', '-500', 'abc', 'NaN', '0', '250.999']) assert.equal(validInterestAmount(invalid), false);
assert.equal(saved[0].source,'vr');
assert.equal(saved[0].amount,121);
assert.equal(saved[2].interested,false);
assert.equal(saved[2].amount,null);
popup.open(startups[0], 'investment');failSave=true;click(250,420);click(800,790);
await new Promise(resolve=>setImmediate(resolve));
assert.ok(has('Nicht gespeichert.'));
assert.equal(has('Ihre Angabe wurde gespeichert.'),false);
failSave=false;click(800,790);await new Promise(resolve=>setImmediate(resolve));
assert.ok(has('Ihre Angabe wurde gespeichert.'));
popup.open(startups[0], 'slides');
assert.ok(has('PREVIEW SLIDE 1 / 3'));
assert.equal(popup.hover({uv:new THREE.Vector2(600/1200, 1-790/900)}),true);
assert.equal(popup.hover({uv:new THREE.Vector2(10/1200, 1-300/900)}),false);
click(600,790);
assert.ok(has('PREVIEW SLIDE 2 / 3'));
const oldPosition=card.position.clone();
camera.position.x+=3;
assert.deepEqual(card.position,oldPosition);
popup.recenter();
assert.ok(card.position.distanceTo(oldPosition)>2.9);
assert.ok(Math.abs(card.position.distanceTo(camera.position)-1.55)<1e-9);
popup.open(startups[7], 'profile');
assert.ok(has('Our Product'));
assert.ok(has('Pre-Seed'));
assert.ok(has('PAGE 1 /'));
click(800,790);
assert.ok(has('PAGE 2 /'));
click(250,790);
assert.ok(has('PAGE 1 /'));
click(1040,65);
assert.equal(popup.active,false);
popup.dispose();
assert.equal(scene.children.length, 1, 'Popup resources removed from scene');
console.log('PASS: booking selection/confirmation/reset, modal closing, job pagination, role switching, sample labels, world anchoring, investment coverage and cleanup.');
